CREATE DATABASE IF NOT EXISTS `orderingSystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

USE `orderingSystem`;

DROP TABLE IF EXISTS `STAFF`;
CREATE TABLE `STAFF` (
  `ID` int(4) NOT NULL AUTO_INCREMENT   COMMENT 'id，使用自增长或特殊算法获得。',
  `STAFF_NAME`  VARCHAR(50) DEFAULT NULL COMMENT '员工名称',
  `PASSWORD` varchar(20) DEFAULT NULL COMMENT '员工密码，可空，管理员必填',
  `LOGIN_NAME` varchar(10)  NULL COMMENT '登录编号',
  `STAFF_TYPE` CHAR(1) NOT NULL COMMENT '员工类型：0：系统管理员 1：跑堂 2：收银 3：外卖人员',
  `STAFF_STATE` CHAR(1) NOT NULL COMMENT '员工状态：0：正常 1：删除',
  `CREATE_TIME` BIGINT(14) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` BIGINT(14) NOT NULL COMMENT '更新时间',

  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_STAFF_L` (`LOGIN_NAME`)

) COMMENT '员工表' ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE `CUSTOMER` (
  `ID` int(6) NOT NULL AUTO_INCREMENT   COMMENT 'id，使用自增长或特殊算法获得。',
  `CUSTOMER_PHONE`  VARCHAR(20) NOT NULL COMMENT '手机号码',
  `CUSTOMER_NAME` varchar(50) DEFAULT NULL COMMENT '名字',
  `CUSTOMER_ADDRESS` varchar(10)  NULL COMMENT '地址',
  `CUSTOMER_RTN` varchar(50) NOT NULL COMMENT 'RTN',
  `CREATE_TIME` BIGINT(14) NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` BIGINT(14) NOT NULL COMMENT '更新时间',

  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CUSTOMER_P` (`CUSTOMER_PHONE`)

) COMMENT '客户信息表' ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


DROP TABLE IF EXISTS `ORDER`;
CREATE TABLE `ORDER` (
  `ID` int(10) NOT NULL AUTO_INCREMENT   COMMENT 'id，使用自增长或特殊算法获得。',
  `ORDER_TYPE`  CHAR(1) NOT NULL COMMENT '订单类型：1：开桌 2：外卖 3：打包',
  `TAKE_OUT_FEE` DOUBLE DEFAULT NULL COMMENT '外卖费',
  `DISH_EXPENSE` DOUBLE DEFAULT NULL COMMENT '菜金',
  `TIP` DOUBLE DEFAULT NULL COMMENT '小费：菜金10%',
  `TAX` DOUBLE DEFAULT NULL COMMENT '税：菜金15%',
  `PRE_PAY` DOUBLE DEFAULT NULL COMMENT '外卖预支费用',
  `PRE_CHANGE` DOUBLE DEFAULT NULL COMMENT '外卖预支找零',
  `TOTAL_FEE` DOUBLE DEFAULT NULL COMMENT '订单总金额',
  `PAY_TYPE` CHAR(1) NOT NULL COMMENT '支付类型：0：现金 1：刷卡',
  `ORDER_CAI` VARCHAR(20) NOT NULL COMMENT 'CAI号',
  `ORDER_RECEIPT_NO` VARCHAR(20) NOT NULL COMMENT '发票号',
  `ORDER_STATE` CHAR(1) NOT NULL COMMENT '订单状态：0：未结账 1：外送 2：完结',
  `IS_URGENT` CHAR(1) NOT NULL COMMENT '是否加急：0：是 1：不是',
  `CUST_NAME` VARCHAR(50) DEFAULT NULL COMMENT '客户名字',
  `CUST_RTN` VARCHAR(20) DEFAULT NULL COMMENT '客户RTN',
  `STAFF_ID` int(4) DEFAULT NULL COMMENT '操作员工ID',
  `CUST_NUM` int(4) DEFAULT NULL COMMENT '人数',
  `FLOOR_TYPE` CHAR(1) DEFAULT NULL COMMENT '楼层:1：一楼 2：二楼',
  `TABLE_NUM` VARCHAR(4) DEFAULT NULL COMMENT '桌号',
	`CREATE_TIME` BIGINT(14) NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` BIGINT(14) NOT NULL COMMENT '更新时间',
  `PAY_TIME` BIGINT(14) NOT NULL COMMENT '支付时间',

  PRIMARY KEY (`ID`)


) COMMENT '订单表' ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


DROP TABLE IF EXISTS `DISH_TYPE`;
CREATE TABLE `DISH_TYPE` (
  `ID` int(10) NOT NULL AUTO_INCREMENT   COMMENT 'id，使用自增长或特殊算法获得。',
  `NAME`  CHAR(1) NOT NULL COMMENT '类别名称',
  `TYPE`  CHAR(1) DEFAULT '1' COMMENT '类别属性：0：饮料 1：其他',

  PRIMARY KEY (`ID`)


) COMMENT '菜的类别表' ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


DROP TABLE IF EXISTS `DISH`;
CREATE TABLE `DISH` (
  `ID` int(10) NOT NULL AUTO_INCREMENT   COMMENT 'id，使用自增长或特殊算法获得。',
  `DISH_TYPE_ID`  int(10) NOT NULL COMMENT '菜的类别表编号：关联菜的类别表',
  `DISH_TYPE`  CHAR(1)  NOT  NULL  COMMENT '类别属性：0：饮料 1：其他',
  `DISH_NAME`  VARCHAR(50)  NOT NULL  COMMENT '菜的名称',
  `DISH_PRICE`  DOUBLE  NOT NULL  COMMENT '菜的单价',
  `DISH_STATE`  CHAR(1)  NOT NULL  COMMENT '菜的状态：0：可售 1：售罄',

  PRIMARY KEY (`ID`)

) COMMENT '菜的详情表' ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


DROP TABLE IF EXISTS `RECEIPT_NUM`;
CREATE TABLE `RECEIPT_NUM` (
  `ID` int(10) NOT NULL AUTO_INCREMENT   COMMENT 'id，使用自增长或特殊算法获得。',
  `START_NUM` int(10) NOT NULL    COMMENT '初始值',
  `END_NUM` int(10) NOT NULL    COMMENT '结束值',
  PRIMARY KEY (`ID`)

) COMMENT '发票号表' ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


DROP TABLE IF EXISTS `ORDER_DETAIL`;
CREATE TABLE `ORDER_DETAIL` (
  `ID` int(10) NOT NULL AUTO_INCREMENT   COMMENT 'id，使用自增长或特殊算法获得。',
  `ORDER_ID` int(10) NOT NULL   COMMENT '订单表id，关联订单表。',
  `DISH_ID` int(10) NOT NULL   COMMENT '菜的详情表id，关联菜的详情表。',
  `DISH_TYPE`  CHAR(1)  NOT  NULL  COMMENT '类别属性：0：饮料 1：其他',
  `DISH_NUM`  INT(4)  NOT  NULL  COMMENT '数量',
  `NOTES`  VARCHAR(200)  NOT  NULL  COMMENT '点单备注',
  `IS_PRINT`  CHAR(1)  NOT  NULL  COMMENT '是否打印：0：是 1：否',

  PRIMARY KEY (`ID`)


) COMMENT '订单详情' ENGINE = InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;


























